include: package:flutter_lints/flutter.yaml

analyzer:
   exclude:
     - lib/generated/**

formatter:
  page_width: 80

linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - curly_braces_in_flow_control_structures
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - public_member_api_docs
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_constructors_first
    - unawaited_futures
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
