arb-dir: l10n/
template-arb-file: en.arb
output-localization-file: clerk_sdk_localizations.dart
output-dir: lib/generated
output-class: ClerkSdkLocalizations
synthetic-package: false
suppress-warnings: true
nullable_getter: false
format: false
header: |-
  // ignore_for_file: public_member_api_docs, use_super_parameters
